FROM golang:1.8

COPY . /go/src/github.com/cyverse-de/de-docker-logging-plugin
WORKDIR /go/src/github.com/cyverse-de/de-docker-logging-plugin

ENV CGO_ENABLED=0

RUN go install

CMD ["/go/bin/de-docker-logging-plugin"]
