FROM golang:1.8

COPY . /project/src/github.com/JinHyukParkk/LoggingDriverTest
WORKDIR /project/src/github.com/JinHyukParkk/LoggingDriverTest

ENV CGO_ENABLED=0

RUN echo "Install start"
RUN go install

CMD ["/go/bin/test-docker-logging-plugin"]
